Explains some errors in test script.

diff --git a/tests/test_only_files_feature b/tests/test_only_files_feature
--- a/tests/test_only_files_feature
+++ b/tests/test_only_files_feature
@@ -27,14 +27,10 @@ set -o errexit
 pushd ${TESTDIR} > /dev/null
 TESTDIR_PATH=$(pwd)
 
-echo t-t0
-
 # Root path of mount point
 ROOT_PATH="${TESTDIR_PATH}/only-files-feature"
 mkdir ${ROOT_PATH}
 sudo mount -t tagvfs ${TESTDIR_PATH}/only-files-feature.tag ${ROOT_PATH}/
-
-echo t-t1
 
 TAGS_DIR=${ROOT_PATH}/tags
 ONLY_FILES_DIR=${ROOT_PATH}/only-files
@@ -44,8 +40,6 @@ ONLY_FILES_DIR=${ROOT_PATH}/only-files
 touch ${TESTDIR_PATH}/only_files_001
 touch ${TESTDIR_PATH}/only_files_002
 ln -s --target-directory="${TAGS_DIR}" "${TESTDIR_PATH}/only_files_001"
-
-echo t-t2
 
 set +o errexit
 ln -s --target-directory="${TAGS_DIR}" "${TESTDIR_PATH}/only_files_001" > /dev/null 2> /dev/null
@@ -57,14 +51,23 @@ set -o errexit
 
 ${SHELL} ${SCRIPT_PATH}/comm_check_exist ${ONLY_FILES_DIR}/only_files_001
 
-echo t-t4
-
+set +o errexit
 ln -s --target-directory="${ONLY_FILES_DIR}" "${TESTDIR_PATH}/only_files_002"
-echo ttz1 ----
-ls ${ONLY_FILES_DIR}
+if [[ $? -ne 0 ]]; then
+  echo "ERROR: ONLY-FILES: Can't create symbol link in only-files directory"
+  exit 1
+fi
 ${SHELL} ${SCRIPT_PATH}/comm_check_exist ${ONLY_FILES_DIR}/only_files_002
-echo tz2
+if [[ $? -ne 0 ]]; then
+  echo "ERROR: ONLY-FILES: Symbol link, created in only-files directory, don't iterated in list of files"
+  exit 1
+fi
 ${SHELL} ${SCRIPT_PATH}/comm_check_exist ${TAGS_DIR}/only_files_002
+if [[ $? -ne 0 ]]; then
+  echo "ERROR: ONLY-FILES: Symbol link, created in only-files directory, don't iterated in list of files in tags directory"
+  exit 1
+fi
+set -o errexit
 
 echo tt1
 # Find unexisted files
